#!/bin/bash

TEMP_PATH=/var/cache/openkeeper
CONFIG_PATH=$TEMP_PATH/config

setconfig() {
	echo $2
	read var
	if [ -z "$var" ] ; then
		echo "$1 未填写，未写入"
		return
	fi

	if [ -f $CONFIG_PATH/$1 ] ; then
		echo "覆盖原$1"
	fi

	echo "$var" > "$CONFIG_PATH/$1"
	chmod 644 "$CONFIG_PATH/$1"
	chown root.root "$CONFIG_PATH/$1"
}

if [ "0" != "$UID" ] ; then
	echo "需要 root 权限"
	exit 1
fi

mkdir -p "$CONFIG_PATH"
cd $CONFIG_PATH

setconfig user "用于拨号的账户(例如：xxxxxx@cqupt )"
setconfig pass "请输入账户密码(例如：password )"

infs="`ip link | awk -F ': ' '/[2-9]:/{print $2}'`"
setconfig eth "用于拨号的网卡(选项：$infs )"

exit 0
