#!/bin/bash

CONFIG_PATH=/etc/openkeeper-cli
CONFIG_NAME=$1

setconfig()
{
    default_value=$(eval echo "\$$1")
    if [ -z $default_value ]; then
        default_value=$3
    fi

    echo -n "$2 [$default_value]: "
	read value
	if [ -z "$value" ] ; then
        value=$default_value
	fi

	echo "$1=\"$value\"" >> "$new_config_name"
	chmod 644 "$new_config_name"
	chown root:root "$new_config_name"
}

if [ "0" != "$UID" ] ; then
	echo "需要 root 权限"
	exit 1
fi

if [ -z "$CONFIG_NAME" ]; then
    CONFIG_NAME="default"
fi
CONFIG_NAME="$CONFIG_PATH/$CONFIG_NAME"

mkdir -p "$CONFIG_PATH"

touch $CONFIG_NAME
. $CONFIG_NAME
new_config_name=$(mktemp)
echo "正在修改配置: $CONFIG_NAME"

setconfig OK_USER "用于拨号的账户(例如：电信手机号@cqupt )"
setconfig OK_PASS "请输入账户密码(默认为身份证号后6位)"
setconfig OK_ETH "用于拨号的网卡(例如 eth0 或 enp0s0)"

echo "=== 以下为高级配置，可以直接按回车使用默认配置 ==="
setconfig OK_IFNAME "PPP 隧道的名字" ppp-ok
setconfig OK_6TO4TUN "6to4 隧道名字" tun-ok6to4
setconfig OK_METRIC "静态路由的跃点数" 0
setconfig OK_RTTABLE "路由表名称" "local"

mv $new_config_name $CONFIG_NAME

echo "配置已写入: $CONFIG_NAME"
exit 0
