#!/bin/bash

# Must be root
if test "`/usr/bin/id -u`" != 0 ; then
    echo "$0: You must be root to run this script" >& 2
    exit 1
fi

TEMP_PATH=~/.openkeeper
# clean up history
rm -rf $TEMP_PATH
rm -f /etc/ppp/pppoe.conf
rm -f /etc/ppp/pap-secrets
echo "处理完毕，openkeeper重置成功，重新配置请用ok-config命令"

exit 0
