#!/bin/bash

CONFIG_PATH=/etc/openkeeper-cli

if [ "0" != "$UID" ]; then
	echo "需要 root 权限"
	exit 1
fi

config=$1
if [ -z $config ]; then
    config="default"
fi
source "$CONFIG_PATH/$config"

kill $(cat "/run/$OK_IFNAME.pid")
ip -6 route flush dev $OK_6TO4TUN
ip link set dev $OK_6TO4TUN down
ip tunnel del $OK_6TO4TUN

echo "已断开连接: $config"
exit 0
